name: Lint, build docker and deploy

on: 
  pull_request:
  push:
    branches:
      - main

env:
  NODE_VERSION: 18

jobs: 
  linting:
    name: Linting 
    runs-on: ubuntu-latest
    steps: 
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Code Linting
        run: npm run lint

  build: 
    needs: linting
    name: Docker build
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - name: Build the latest Docker image
          run: docker build . --file Dockerfile --tag ximikboda/myapp:latest

        - name: Save docker docker to temp directory
          run: mkdir -p /tmp/share
          run: docker save ximikboda/myapp:latest > /tmp/share/docker-image.tar

        - name: Temporarily save Docker image
          uses: actions/upload-artifact@v2
          with:
            name: docker-artifact
            path: /tmp/share/
            retention-days: 1

  deploy:
    needs: build
    name: Docker deploy 
    runs-on: ubuntu-latest
    steps:
        - name: Retrieve saved Docker image
          uses: actions/download-artifact@v2
          with:
            name: docker-artifact
            path: /tmp/share/

        - name: Docker load
          run: docker load < /tmp/share/docker-image.tar

        - name: Login
          run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

        - name: Push
          run: docker push ximikboda/myapp:latest
       

  
